
#set the spring boot application name
spring.application.name=weather-api

#reads the weather API key - from an environemt variable caleld weather api key 
weather.api.key=${WEATHER_API_KEY}

#stores the base url for the visal crossing weathe rapi 
weather.api.base-url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline

#reads the redis host from redis host or uses localhost by deafualt 
spring.data.redis.hot=${REDIS_HOST:localhost}

#redis the redis port form redis port or uses 6379
spring.data.redis.port=${REDIS_PORT:6379}

#runs the spring boot api on port 8080
server.port=8080